/**
 * Supabase data-access layer for FinVerse AI.
 *
 * Every function is scoped to the signed-in user: the user id is resolved via
 * `uid()` and attached to every query (RLS enforces it server-side as well).
 *
 * ASSUMED SCHEMA (must match the migrations worker):
 *   tables: transactions, budgets, bills, goals, holdings, accounts,
 *           custom_categories, recurring_rules
 *   every table: id uuid PK default gen_random_uuid(),
 *                user_id uuid not null,
 *                created_at / updated_at timestamptz default now()
 *   transactions: type text, amount_paise int, category text, note text,
 *     date_iso date, pay_mode text, goal_id uuid null, bill_id uuid null,
 *     account_id uuid null, to_account_id uuid null, tags text[] default '{}',
 *     recurring_rule_id uuid null
 *   budgets: category_id text, month text ("YYYY-MM"), limit_paise int,
 *     unique (user_id, category_id, month)
 *   bills: name text, amount_paise int, due_day int, category text,
 *     last_paid_on date null
 *   goals: name text, target_paise int, saved_paise int, deadline date, color text
 *   holdings: symbol text, qty numeric, avg_price_paise int
 *   accounts: name text, type text, icon_name text, color text,
 *     opening_balance_paise int, is_default bool default false
 *   custom_categories: label text, icon_name text, color text, kind text
 *   recurring_rules: type text, amount_paise int, category text, note text,
 *     pay_mode text, account_id uuid null, to_account_id uuid null,
 *     tags text[] default '{}', frequency text, start_date_iso date,
 *     end_date_iso date null, last_posted_date_iso date null, is_paused bool default false
 */

// Forward reference: src/lib/supabase.ts is provided by the auth worker at
// integration time. This import is intentional even though the module does
// not exist yet in this workdir.
import { getSupabase } from "@/lib/supabase";
import type {
  Account,
  AccountType,
  Bill,
  Budget,
  CustomCategory,
  FinanceDB,
  Goal,
  Holding,
  PayMode,
  RecurringFrequency,
  RecurringRule,
  Transaction,
  TransactionType,
} from "./types";
import { setCustomCategoryCache } from "./categories";
import { todayISO } from "./format";

/** New-record input shapes (ids/timestamps are generated by the database). */
export type NewTransaction = Omit<Transaction, "id" | "createdAt" | "updatedAt">;
export type NewAccount = Pick<
  Account,
  "name" | "type" | "iconName" | "color" | "openingBalancePaise"
> & { isDefault?: boolean };
export type NewCustomCategory = Pick<CustomCategory, "label" | "iconName" | "color" | "kind">;
export type NewRecurringRule = Omit<
  RecurringRule,
  "id" | "createdAt" | "updatedAt" | "lastPostedDateISO" | "isPaused"
> & { isPaused?: boolean };

/** Patch shape for updateRecurringRule. */
export type RecurringRulePatch = Partial<
  Pick<
    RecurringRule,
    | "type"
    | "amountPaise"
    | "category"
    | "note"
    | "payMode"
    | "accountId"
    | "toAccountId"
    | "frequency"
    | "startDateISO"
    | "endDateISO"
    | "isPaused"
  >
> & { tags?: string[] };

/** Account with its live (derived) balance. */
export interface AccountSummary {
  account: Account;
  balancePaise: number;
}

// ---- internal: auth + query plumbing ----

/** Current user id; throws a clear error when there is no signed-in user. */
async function uid(): Promise<string> {
  const { data } = await getSupabase().auth.getUser();
  const id = data.user?.id;
  if (!id) {
    throw new Error(
      "Not signed in: Supabase auth.getUser() returned no user. Sign in before accessing finance data.",
    );
  }
  return id;
}

function isNoRows(error: { code?: string } | null | undefined): boolean {
  return !!error && error.code === "PGRST116";
}

// ---- internal: validation (ported from store.ts) ----

function assertPaise(amountPaise: number): void {
  if (!Number.isInteger(amountPaise) || amountPaise < 0) {
    throw new Error(`Amount must be a non-negative integer number of paise, got ${amountPaise}`);
  }
}

function assertDateISO(value: string, field: string): void {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value) || Number.isNaN(new Date(`${value}T12:00:00`).getTime())) {
    throw new Error(`${field} must be a valid YYYY-MM-DD date, got "${value}"`);
  }
}

const HEX_COLOR = /^#[0-9a-fA-F]{6}$/;

/** Trim, drop empties, dedupe (case-insensitive), cap count/length. */
function normalizeTags(tags: unknown): string[] {
  if (!Array.isArray(tags)) return [];
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of tags) {
    if (typeof raw !== "string") continue;
    const t = raw.trim().slice(0, 24);
    if (!t) continue;
    const key = t.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(t);
    if (out.length >= 10) break;
  }
  return out;
}

// ---- internal: recurring date math (ported from store.ts; do not import) ----

function pad2(n: number): string {
  return String(n).padStart(2, "0");
}

function addDaysISO(iso: string, days: number): string {
  const parts = iso.split("-").map(Number);
  const y = parts[0] ?? 1970;
  const m = parts[1] ?? 1;
  const d = parts[2] ?? 1;
  const dt = new Date(y, m - 1, d);
  dt.setDate(dt.getDate() + days);
  return `${dt.getFullYear()}-${pad2(dt.getMonth() + 1)}-${pad2(dt.getDate())}`;
}

/** Shift a date by whole months, clamping the day to the target month length. */
function addMonthsClamped(y: number, m: number, d: number, delta: number): string {
  const total = y * 12 + (m - 1) + delta;
  const ny = Math.floor(total / 12);
  const nm = (total % 12) + 1;
  const daysInMonth = new Date(ny, nm, 0).getDate();
  return `${ny}-${pad2(nm)}-${pad2(Math.min(d, daysInMonth))}`;
}

/** The nth occurrence date of a rule, computed from its start (no drift). */
function recurringOccurrenceDate(
  startDateISO: string,
  frequency: RecurringFrequency,
  n: number,
): string {
  const parts = startDateISO.split("-").map(Number);
  const y = parts[0] ?? 1970;
  const m = parts[1] ?? 1;
  const d = parts[2] ?? 1;
  switch (frequency) {
    case "daily":
      return addDaysISO(startDateISO, n);
    case "weekly":
      return addDaysISO(startDateISO, n * 7);
    case "monthly":
      return addMonthsClamped(y, m, d, n);
    case "yearly":
      return addMonthsClamped(y, m, d, n * 12);
  }
}

const FREQUENCIES: RecurringFrequency[] = ["daily", "weekly", "monthly", "yearly"];

function assertRuleInput(input: {
  type: TransactionType;
  amountPaise: number;
  startDateISO: string;
  endDateISO?: string;
  frequency: RecurringFrequency;
}): void {
  if (input.type !== "expense" && input.type !== "income" && input.type !== "transfer") {
    throw new Error("Recurring rule type must be expense, income, or transfer.");
  }
  assertPaise(input.amountPaise);
  if (input.amountPaise === 0) throw new Error("Recurring amount must be greater than zero.");
  if (!FREQUENCIES.includes(input.frequency)) throw new Error("Invalid frequency.");
  assertDateISO(input.startDateISO, "startDateISO");
  if (input.endDateISO !== undefined) {
    assertDateISO(input.endDateISO, "endDateISO");
    if (input.endDateISO < input.startDateISO) {
      throw new Error("End date cannot be before the start date.");
    }
  }
}

// ---- internal: row types + mappers (snake_case <-> camelCase) ----

interface TransactionRow {
  id: string;
  type: TransactionType;
  amount_paise: number;
  category: string;
  note: string;
  date_iso: string;
  pay_mode: PayMode;
  goal_id: string | null;
  bill_id: string | null;
  account_id: string | null;
  to_account_id: string | null;
  tags: string[] | null;
  recurring_rule_id: string | null;
  created_at: string;
  updated_at: string;
}

interface BudgetRow {
  id: string;
  category_id: string;
  month: string;
  limit_paise: number;
}

interface BillRow {
  id: string;
  name: string;
  amount_paise: number;
  due_day: number;
  category: string;
  last_paid_on: string | null;
}

interface GoalRow {
  id: string;
  name: string;
  target_paise: number;
  saved_paise: number;
  deadline: string;
  color: string;
}

interface HoldingRow {
  id: string;
  symbol: string;
  qty: number;
  avg_price_paise: number;
}

interface AccountRow {
  id: string;
  name: string;
  type: AccountType;
  icon_name: string;
  color: string;
  opening_balance_paise: number;
  is_default: boolean;
  created_at: string;
  updated_at: string;
}

interface CustomCategoryRow {
  id: string;
  label: string;
  icon_name: string;
  color: string;
  kind: CustomCategory["kind"];
  created_at: string;
  updated_at: string;
}

interface RecurringRuleRow {
  id: string;
  type: TransactionType;
  amount_paise: number;
  category: string;
  note: string;
  pay_mode: PayMode;
  account_id: string | null;
  to_account_id: string | null;
  tags: string[] | null;
  frequency: RecurringFrequency;
  start_date_iso: string;
  end_date_iso: string | null;
  last_posted_date_iso: string | null;
  is_paused: boolean;
  created_at: string;
  updated_at: string;
}

function toTransaction(row: TransactionRow): Transaction {
  return {
    id: row.id,
    type: row.type,
    amountPaise: row.amount_paise,
    category: row.category,
    note: row.note,
    dateISO: row.date_iso,
    payMode: row.pay_mode,
    ...(row.goal_id ? { goalId: row.goal_id } : {}),
    ...(row.bill_id ? { billId: row.bill_id } : {}),
    ...(row.account_id ? { accountId: row.account_id } : {}),
    ...(row.to_account_id ? { toAccountId: row.to_account_id } : {}),
    tags: row.tags ?? [],
    ...(row.recurring_rule_id ? { recurringRuleId: row.recurring_rule_id } : {}),
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

function toBudget(row: BudgetRow): Budget {
  return { id: row.id, categoryId: row.category_id, month: row.month, limitPaise: row.limit_paise };
}

function toBill(row: BillRow): Bill {
  return {
    id: row.id,
    name: row.name,
    amountPaise: row.amount_paise,
    dueDay: row.due_day,
    category: row.category,
    ...(row.last_paid_on ? { lastPaidOn: row.last_paid_on } : {}),
  };
}

function toGoal(row: GoalRow): Goal {
  return {
    id: row.id,
    name: row.name,
    targetPaise: row.target_paise,
    savedPaise: row.saved_paise,
    deadline: row.deadline,
    color: row.color,
  };
}

function toHolding(row: HoldingRow): Holding {
  return { id: row.id, symbol: row.symbol, qty: row.qty, avgPricePaise: row.avg_price_paise };
}

function toAccount(row: AccountRow): Account {
  return {
    id: row.id,
    name: row.name,
    type: row.type,
    iconName: row.icon_name,
    color: row.color,
    openingBalancePaise: row.opening_balance_paise,
    isDefault: row.is_default,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

function toCustomCategory(row: CustomCategoryRow): CustomCategory {
  return {
    id: row.id,
    label: row.label,
    iconName: row.icon_name,
    color: row.color,
    kind: row.kind,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

function toRecurringRule(row: RecurringRuleRow): RecurringRule {
  return {
    id: row.id,
    type: row.type,
    amountPaise: row.amount_paise,
    category: row.category,
    note: row.note,
    payMode: row.pay_mode,
    ...(row.account_id ? { accountId: row.account_id } : {}),
    ...(row.to_account_id ? { toAccountId: row.to_account_id } : {}),
    tags: row.tags ?? [],
    frequency: row.frequency,
    startDateISO: row.start_date_iso,
    ...(row.end_date_iso ? { endDateISO: row.end_date_iso } : {}),
    lastPostedDateISO: row.last_posted_date_iso,
    isPaused: row.is_paused,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

const DEFAULT_ICON_FOR_TYPE: Record<AccountType, string> = {
  cash: "wallet",
  upi: "smartphone",
  bank: "bank",
};

function monthRange(month: string): { from: string; to: string } {
  const m = /^(\d{4})-(\d{2})$/.exec(month);
  const y = Number(m?.[1] ?? 0);
  const mo = Number(m?.[2] ?? 0);
  if (!m || y < 1000 || mo < 1 || mo > 12) {
    throw new Error(`month must be "YYYY-MM", got "${month}"`);
  }
  const toY = mo === 12 ? y + 1 : y;
  const toM = mo === 12 ? 1 : mo + 1;
  return { from: `${month}-01`, to: `${toY}-${String(toM).padStart(2, "0")}-01` };
}

// ---- Transactions ----

/** All transactions, newest first; optional "YYYY-MM" filter on the date. */
export async function fetchTransactions(month?: string): Promise<Transaction[]> {
  const userId = await uid();
  const sb = getSupabase();
  let q = sb
    .from("transactions")
    .select()
    .eq("user_id", userId)
    .order("date_iso", { ascending: false })
    .order("created_at", { ascending: false });
  if (month) {
    const { from, to } = monthRange(month);
    q = q.gte("date_iso", from).lt("date_iso", to);
  }
  const { data, error } = await q;
  if (error) throw error;
  return ((data ?? []) as unknown as TransactionRow[]).map(toTransaction);
}

export async function insertTransaction(input: NewTransaction): Promise<Transaction> {
  assertPaise(input.amountPaise);
  assertDateISO(input.dateISO, "dateISO");
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("transactions")
    .insert({
      user_id: userId,
      type: input.type,
      amount_paise: input.amountPaise,
      category: input.category,
      note: input.note,
      date_iso: input.dateISO,
      pay_mode: input.payMode,
      ...(input.goalId ? { goal_id: input.goalId } : {}),
      ...(input.billId ? { bill_id: input.billId } : {}),
      ...(input.accountId ? { account_id: input.accountId } : {}),
      ...(input.toAccountId ? { to_account_id: input.toAccountId } : {}),
      tags: normalizeTags(input.tags),
      ...(input.recurringRuleId ? { recurring_rule_id: input.recurringRuleId } : {}),
    })
    .select()
    .single();
  if (error) throw error;
  return toTransaction(data as unknown as TransactionRow);
}

export async function updateTransaction(
  id: string,
  patch: Partial<Omit<Transaction, "id" | "createdAt">>,
): Promise<Transaction | undefined> {
  if (patch.amountPaise !== undefined) assertPaise(patch.amountPaise);
  if (patch.dateISO !== undefined) assertDateISO(patch.dateISO, "dateISO");
  const userId = await uid();
  const sb = getSupabase();
  const row: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (patch.type !== undefined) row["type"] = patch.type;
  if (patch.amountPaise !== undefined) row["amount_paise"] = patch.amountPaise;
  if (patch.category !== undefined) row["category"] = patch.category;
  if (patch.note !== undefined) row["note"] = patch.note;
  if (patch.dateISO !== undefined) row["date_iso"] = patch.dateISO;
  if (patch.payMode !== undefined) row["pay_mode"] = patch.payMode;
  if (patch.goalId !== undefined) row["goal_id"] = patch.goalId;
  if (patch.billId !== undefined) row["bill_id"] = patch.billId;
  if (patch.accountId !== undefined) row["account_id"] = patch.accountId;
  if (patch.toAccountId !== undefined) row["to_account_id"] = patch.toAccountId;
  if (patch.tags !== undefined) row["tags"] = normalizeTags(patch.tags);
  if (patch.recurringRuleId !== undefined) row["recurring_rule_id"] = patch.recurringRuleId;
  const { data, error } = await sb
    .from("transactions")
    .update(row)
    .eq("id", id)
    .eq("user_id", userId)
    .select()
    .single();
  if (isNoRows(error)) return undefined;
  if (error) throw error;
  return toTransaction(data as unknown as TransactionRow);
}

export async function deleteTransaction(id: string): Promise<boolean> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("transactions")
    .delete()
    .eq("id", id)
    .eq("user_id", userId)
    .select("id");
  if (error) throw error;
  return ((data ?? []) as unknown[]).length > 0;
}

/** Record an account-to-account transfer as a single transfer transaction. */
export async function transferBetweenAccounts(input: {
  fromAccountId: string;
  toAccountId: string;
  amountPaise: number;
  note?: string;
  dateISO?: string;
}): Promise<Transaction> {
  assertPaise(input.amountPaise);
  if (input.amountPaise === 0) throw new Error("Transfer amount must be greater than zero.");
  if (input.fromAccountId === input.toAccountId) {
    throw new Error("Pick two different accounts for a transfer.");
  }
  const accounts = await fetchAccounts();
  const from = accounts.find((a) => a.id === input.fromAccountId);
  const to = accounts.find((a) => a.id === input.toAccountId);
  if (!from || !to) throw new Error("Both accounts must exist.");
  const dateISO = input.dateISO ?? todayISO();
  assertDateISO(dateISO, "dateISO");
  return insertTransaction({
    type: "transfer",
    amountPaise: input.amountPaise,
    category: "others",
    note: input.note?.trim() || `Transfer · ${from.name} → ${to.name}`,
    dateISO,
    payMode: "Bank",
    accountId: from.id,
    toAccountId: to.id,
    tags: [],
  });
}

// ---- Budgets ----

export async function fetchBudgets(month: string): Promise<Budget[]> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("budgets")
    .select()
    .eq("user_id", userId)
    .eq("month", month)
    .order("category_id");
  if (error) throw error;
  return ((data ?? []) as unknown as BudgetRow[]).map(toBudget);
}

async function fetchAllBudgets(): Promise<Budget[]> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("budgets")
    .select()
    .eq("user_id", userId)
    .order("month")
    .order("category_id");
  if (error) throw error;
  return ((data ?? []) as unknown as BudgetRow[]).map(toBudget);
}

/** Upsert on (user_id, category_id, month): creates or replaces the budget. */
export async function setBudget(input: {
  categoryId: string;
  month: string;
  limitPaise: number;
}): Promise<Budget> {
  assertPaise(input.limitPaise);
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("budgets")
    .upsert(
      {
        user_id: userId,
        category_id: input.categoryId,
        month: input.month,
        limit_paise: input.limitPaise,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "user_id,category_id,month" },
    )
    .select()
    .single();
  if (error) throw error;
  return toBudget(data as unknown as BudgetRow);
}

// ---- Bills ----

export async function fetchBills(): Promise<Bill[]> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb.from("bills").select().eq("user_id", userId).order("due_day");
  if (error) throw error;
  return ((data ?? []) as unknown as BillRow[]).map(toBill);
}

/**
 * Marks a bill paid (sets last_paid_on) AND inserts the matching expense
 * transaction against the default account.
 */
export async function markBillPaid(id: string, dateISO: string): Promise<Bill | undefined> {
  assertDateISO(dateISO, "dateISO");
  const userId = await uid();
  const sb = getSupabase();
  const now = new Date().toISOString();
  const { data, error } = await sb
    .from("bills")
    .update({ last_paid_on: dateISO, updated_at: now })
    .eq("id", id)
    .eq("user_id", userId)
    .select()
    .single();
  if (isNoRows(error)) return undefined;
  if (error) throw error;
  const bill = toBill(data as unknown as BillRow);
  const fallbackAccountId = await defaultAccountId();
  await insertTransaction({
    type: "expense",
    amountPaise: bill.amountPaise,
    category: bill.category,
    note: `${bill.name} bill paid`,
    dateISO,
    payMode: "UPI",
    ...(fallbackAccountId ? { accountId: fallbackAccountId } : {}),
    billId: bill.id,
    tags: [],
  });
  return bill;
}

/** Insert a new bill (id generated by the database). */
export async function insertBill(input: Omit<Bill, "id">): Promise<Bill> {
  const name = input.name.trim();
  if (!name) throw new Error("Bill name is required.");
  assertPaise(input.amountPaise);
  if (!Number.isInteger(input.dueDay) || input.dueDay < 1 || input.dueDay > 31) {
    throw new Error("Bill due day must be an integer between 1 and 31.");
  }
  if (input.lastPaidOn !== undefined) assertDateISO(input.lastPaidOn, "lastPaidOn");
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("bills")
    .insert({
      user_id: userId,
      name: name.slice(0, 60),
      amount_paise: input.amountPaise,
      due_day: input.dueDay,
      category: input.category,
      last_paid_on: input.lastPaidOn ?? null,
    })
    .select()
    .single();
  if (error) throw error;
  return toBill(data as unknown as BillRow);
}

/** Update a bill's fields. Returns undefined when the bill does not exist. */
export async function updateBill(
  id: string,
  patch: Partial<Omit<Bill, "id">>,
): Promise<Bill | undefined> {
  if (patch.name !== undefined && !patch.name.trim()) throw new Error("Bill name is required.");
  if (patch.amountPaise !== undefined) assertPaise(patch.amountPaise);
  if (
    patch.dueDay !== undefined &&
    (!Number.isInteger(patch.dueDay) || patch.dueDay < 1 || patch.dueDay > 31)
  ) {
    throw new Error("Bill due day must be an integer between 1 and 31.");
  }
  if (patch.lastPaidOn !== undefined) assertDateISO(patch.lastPaidOn, "lastPaidOn");
  const userId = await uid();
  const sb = getSupabase();
  const row: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (patch.name !== undefined) row["name"] = patch.name.trim().slice(0, 60);
  if (patch.amountPaise !== undefined) row["amount_paise"] = patch.amountPaise;
  if (patch.dueDay !== undefined) row["due_day"] = patch.dueDay;
  if (patch.category !== undefined) row["category"] = patch.category;
  if (patch.lastPaidOn !== undefined) row["last_paid_on"] = patch.lastPaidOn;
  const { data, error } = await sb
    .from("bills")
    .update(row)
    .eq("id", id)
    .eq("user_id", userId)
    .select()
    .single();
  if (isNoRows(error)) return undefined;
  if (error) throw error;
  return toBill(data as unknown as BillRow);
}

/** Delete a bill. Past payment transactions are kept. */
export async function deleteBill(id: string): Promise<boolean> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("bills")
    .delete()
    .eq("id", id)
    .eq("user_id", userId)
    .select("id");
  if (error) throw error;
  return ((data ?? []) as unknown[]).length > 0;
}

// ---- Goals ----

export async function fetchGoals(): Promise<Goal[]> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb.from("goals").select().eq("user_id", userId).order("created_at");
  if (error) throw error;
  return ((data ?? []) as unknown as GoalRow[]).map(toGoal);
}

export async function insertGoal(input: Omit<Goal, "id">): Promise<Goal> {
  assertPaise(input.targetPaise);
  assertPaise(input.savedPaise);
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("goals")
    .insert({
      user_id: userId,
      name: input.name,
      target_paise: input.targetPaise,
      saved_paise: input.savedPaise,
      deadline: input.deadline,
      color: input.color,
    })
    .select()
    .single();
  if (error) throw error;
  return toGoal(data as unknown as GoalRow);
}

export async function updateGoal(
  id: string,
  patch: Partial<Omit<Goal, "id">>,
): Promise<Goal | undefined> {
  if (patch.targetPaise !== undefined) assertPaise(patch.targetPaise);
  if (patch.savedPaise !== undefined) assertPaise(patch.savedPaise);
  const userId = await uid();
  const sb = getSupabase();
  const row: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (patch.name !== undefined) row["name"] = patch.name;
  if (patch.targetPaise !== undefined) row["target_paise"] = patch.targetPaise;
  if (patch.savedPaise !== undefined) row["saved_paise"] = patch.savedPaise;
  if (patch.deadline !== undefined) row["deadline"] = patch.deadline;
  if (patch.color !== undefined) row["color"] = patch.color;
  const { data, error } = await sb
    .from("goals")
    .update(row)
    .eq("id", id)
    .eq("user_id", userId)
    .select()
    .single();
  if (isNoRows(error)) return undefined;
  if (error) throw error;
  return toGoal(data as unknown as GoalRow);
}

export async function deleteGoal(id: string): Promise<boolean> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("goals")
    .delete()
    .eq("id", id)
    .eq("user_id", userId)
    .select("id");
  if (error) throw error;
  return ((data ?? []) as unknown[]).length > 0;
}

/**
 * Adds funds to a goal: bumps saved_paise (clamped at the target) AND inserts
 * the matching transfer transaction against the default account.
 */
export async function addFundsToGoal(
  id: string,
  amountPaise: number,
  note?: string,
): Promise<Goal | undefined> {
  assertPaise(amountPaise);
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("goals")
    .select()
    .eq("id", id)
    .eq("user_id", userId)
    .single();
  if (isNoRows(error)) return undefined;
  if (error) throw error;
  const goal = toGoal(data as unknown as GoalRow);
  const savedPaise = Math.min(goal.targetPaise, goal.savedPaise + amountPaise);
  const { data: updated, error: updateError } = await sb
    .from("goals")
    .update({ saved_paise: savedPaise, updated_at: new Date().toISOString() })
    .eq("id", id)
    .eq("user_id", userId)
    .select()
    .single();
  if (updateError) throw updateError;
  const fallbackAccountId = await defaultAccountId();
  await insertTransaction({
    type: "transfer",
    amountPaise,
    category: "investments",
    note: note ?? `Saved towards ${goal.name}`,
    dateISO: todayISO(),
    payMode: "Bank",
    ...(fallbackAccountId ? { accountId: fallbackAccountId } : {}),
    goalId: goal.id,
    tags: [],
  });
  return toGoal(updated as unknown as GoalRow);
}

// ---- Holdings ----

export async function fetchHoldings(): Promise<Holding[]> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb.from("holdings").select().eq("user_id", userId).order("symbol");
  if (error) throw error;
  return ((data ?? []) as unknown as HoldingRow[]).map(toHolding);
}

export async function insertHolding(input: Omit<Holding, "id">): Promise<Holding> {
  assertPaise(input.avgPricePaise);
  if (!Number.isFinite(input.qty) || input.qty < 0) {
    throw new Error("Holding qty must be a non-negative number");
  }
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("holdings")
    .insert({
      user_id: userId,
      symbol: input.symbol,
      qty: input.qty,
      avg_price_paise: input.avgPricePaise,
    })
    .select()
    .single();
  if (error) throw error;
  return toHolding(data as unknown as HoldingRow);
}

export async function updateHolding(
  id: string,
  patch: Partial<Omit<Holding, "id">>,
): Promise<Holding | undefined> {
  if (patch.avgPricePaise !== undefined) assertPaise(patch.avgPricePaise);
  if (patch.qty !== undefined && (!Number.isFinite(patch.qty) || patch.qty < 0)) {
    throw new Error("Holding qty must be a non-negative number");
  }
  const userId = await uid();
  const sb = getSupabase();
  const row: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (patch.symbol !== undefined) row["symbol"] = patch.symbol;
  if (patch.qty !== undefined) row["qty"] = patch.qty;
  if (patch.avgPricePaise !== undefined) row["avg_price_paise"] = patch.avgPricePaise;
  const { data, error } = await sb
    .from("holdings")
    .update(row)
    .eq("id", id)
    .eq("user_id", userId)
    .select()
    .single();
  if (isNoRows(error)) return undefined;
  if (error) throw error;
  return toHolding(data as unknown as HoldingRow);
}

export async function deleteHolding(id: string): Promise<boolean> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("holdings")
    .delete()
    .eq("id", id)
    .eq("user_id", userId)
    .select("id");
  if (error) throw error;
  return ((data ?? []) as unknown[]).length > 0;
}

// ---- Accounts ----

export async function fetchAccounts(): Promise<Account[]> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("accounts")
    .select()
    .eq("user_id", userId)
    .order("created_at");
  if (error) throw error;
  return ((data ?? []) as unknown as AccountRow[]).map(toAccount);
}

export async function insertAccount(input: NewAccount): Promise<Account> {
  const name = input.name.trim();
  if (!name) throw new Error("Account name is required.");
  assertPaise(input.openingBalancePaise);
  if (!HEX_COLOR.test(input.color)) throw new Error("Account color must be a hex color.");
  const userId = await uid();
  const sb = getSupabase();
  const existing = await fetchAccounts();
  const makeDefault = input.isDefault === true || existing.length === 0;
  if (makeDefault && existing.length > 0) {
    const { error } = await sb.from("accounts").update({ is_default: false }).eq("user_id", userId);
    if (error) throw error;
  }
  const { data, error } = await sb
    .from("accounts")
    .insert({
      user_id: userId,
      name: name.slice(0, 40),
      type: input.type,
      icon_name: input.iconName || DEFAULT_ICON_FOR_TYPE[input.type],
      color: input.color,
      opening_balance_paise: input.openingBalancePaise,
      is_default: makeDefault,
    })
    .select()
    .single();
  if (error) throw error;
  return toAccount(data as unknown as AccountRow);
}

export async function updateAccount(
  id: string,
  patch: Partial<Pick<Account, "name" | "type" | "iconName" | "color" | "openingBalancePaise">>,
): Promise<Account | undefined> {
  const userId = await uid();
  const sb = getSupabase();
  const row: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (patch.name !== undefined) {
    const name = patch.name.trim();
    if (!name) throw new Error("Account name is required.");
    row["name"] = name.slice(0, 40);
  }
  if (patch.type !== undefined) row["type"] = patch.type;
  if (patch.iconName !== undefined) row["icon_name"] = patch.iconName;
  if (patch.color !== undefined) {
    if (!HEX_COLOR.test(patch.color)) throw new Error("Account color must be a hex color.");
    row["color"] = patch.color;
  }
  if (patch.openingBalancePaise !== undefined) {
    assertPaise(patch.openingBalancePaise);
    row["opening_balance_paise"] = patch.openingBalancePaise;
  }
  const { data, error } = await sb
    .from("accounts")
    .update(row)
    .eq("id", id)
    .eq("user_id", userId)
    .select()
    .single();
  if (isNoRows(error)) return undefined;
  if (error) throw error;
  return toAccount(data as unknown as AccountRow);
}

/**
 * Deletes an account and re-points its transactions (and recurring rules) at
 * the default account, so no history is lost. Throws when the account is the
 * default or the last one — pick/set another default first.
 */
export async function deleteAccount(id: string): Promise<void> {
  const userId = await uid();
  const sb = getSupabase();
  const accounts = await fetchAccounts();
  const account = accounts.find((a) => a.id === id);
  if (!account) throw new Error("Account not found.");
  if (accounts.length === 1) {
    throw new Error("You need at least one account — create another before deleting this one.");
  }
  if (account.isDefault) {
    throw new Error("This is your default account. Set another account as default first.");
  }
  const fallback = accounts.find((a) => a.isDefault) ?? accounts.find((a) => a.id !== id);
  if (!fallback) throw new Error("No fallback account found.");
  for (const table of ["transactions", "recurring_rules"] as const) {
    const { error: e1 } = await sb
      .from(table)
      .update({ account_id: fallback.id })
      .eq("user_id", userId)
      .eq("account_id", id);
    if (e1) throw e1;
    const { error: e2 } = await sb
      .from(table)
      .update({ to_account_id: fallback.id })
      .eq("user_id", userId)
      .eq("to_account_id", id);
    if (e2) throw e2;
  }
  const { error } = await sb.from("accounts").delete().eq("id", id).eq("user_id", userId);
  if (error) throw error;
}

export async function setDefaultAccount(id: string): Promise<Account> {
  const userId = await uid();
  const sb = getSupabase();
  const accounts = await fetchAccounts();
  const account = accounts.find((a) => a.id === id);
  if (!account) throw new Error("Account not found.");
  const { error: clearError } = await sb
    .from("accounts")
    .update({ is_default: false })
    .eq("user_id", userId);
  if (clearError) throw clearError;
  const now = new Date().toISOString();
  const { data, error } = await sb
    .from("accounts")
    .update({ is_default: true, updated_at: now })
    .eq("id", id)
    .eq("user_id", userId)
    .select()
    .single();
  if (error) throw error;
  return toAccount(data as unknown as AccountRow);
}

/** The account new transactions default to; falls back to the first account. */
export async function defaultAccountId(): Promise<string | undefined> {
  const accounts = await fetchAccounts();
  return accounts.find((a) => a.isDefault)?.id ?? accounts[0]?.id;
}

/**
 * Live balance: opening balance plus replayed transaction effects.
 * Expense debits, income credits; transfers debit the source account and
 * credit the destination account. Always consistent — edits/deletes flow
 * through automatically because the balance is derived, not stored.
 */
export function balanceForAccount(account: Account, transactions: Transaction[]): number {
  let balance = account.openingBalancePaise;
  for (const t of transactions) {
    if (t.type === "transfer") {
      if (t.accountId === account.id) balance -= t.amountPaise;
      if (t.toAccountId === account.id) balance += t.amountPaise;
    } else if (t.accountId === account.id) {
      balance += t.type === "income" ? t.amountPaise : -t.amountPaise;
    }
  }
  return balance;
}

/** Accounts with live balances, computed client-side from all transactions. */
export async function fetchAccountSummaries(): Promise<AccountSummary[]> {
  const [accounts, transactions] = await Promise.all([fetchAccounts(), fetchTransactions()]);
  return accounts.map((account) => ({
    account,
    balancePaise: balanceForAccount(account, transactions),
  }));
}

// ---- Custom categories ----

export async function fetchCustomCategories(): Promise<CustomCategory[]> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("custom_categories")
    .select()
    .eq("user_id", userId)
    .order("label");
  if (error) throw error;
  const list = ((data ?? []) as unknown as CustomCategoryRow[]).map(toCustomCategory);
  // Keep the synchronous category lookup (categories.ts) in sync.
  setCustomCategoryCache(list);
  return list;
}

export async function insertCustomCategory(input: NewCustomCategory): Promise<CustomCategory> {
  const label = input.label.trim();
  if (!label) throw new Error("Category name is required.");
  if (!HEX_COLOR.test(input.color)) throw new Error("Color must be a hex color.");
  const existing = await fetchCustomCategories();
  const clash =
    existing.some((c) => c.label.toLowerCase() === label.toLowerCase()) ||
    label.toLowerCase() === "others";
  if (clash) throw new Error("A category with this name already exists.");
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("custom_categories")
    .insert({
      user_id: userId,
      label: label.slice(0, 30),
      icon_name: input.iconName || "tag",
      color: input.color,
      kind: input.kind,
    })
    .select()
    .single();
  if (error) throw error;
  return toCustomCategory(data as unknown as CustomCategoryRow);
}

export async function updateCustomCategory(
  id: string,
  patch: Partial<Pick<CustomCategory, "label" | "iconName" | "color">>,
): Promise<CustomCategory | undefined> {
  const userId = await uid();
  const sb = getSupabase();
  const row: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (patch.label !== undefined) {
    const label = patch.label.trim();
    if (!label) throw new Error("Category name is required.");
    const existing = await fetchCustomCategories();
    const clash = existing.some(
      (c) => c.id !== id && c.label.toLowerCase() === label.toLowerCase(),
    );
    if (clash) throw new Error("A category with this name already exists.");
    row["label"] = label.slice(0, 30);
  }
  if (patch.iconName !== undefined) row["icon_name"] = patch.iconName;
  if (patch.color !== undefined) {
    if (!HEX_COLOR.test(patch.color)) throw new Error("Color must be a hex color.");
    row["color"] = patch.color;
  }
  const { data, error } = await sb
    .from("custom_categories")
    .update(row)
    .eq("id", id)
    .eq("user_id", userId)
    .select()
    .single();
  if (isNoRows(error)) return undefined;
  if (error) throw error;
  return toCustomCategory(data as unknown as CustomCategoryRow);
}

export async function deleteCustomCategory(id: string): Promise<boolean> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("custom_categories")
    .delete()
    .eq("id", id)
    .eq("user_id", userId)
    .select("id");
  if (error) throw error;
  return ((data ?? []) as unknown[]).length > 0;
}

// ---- Recurring rules ----

export async function fetchRecurringRules(): Promise<RecurringRule[]> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("recurring_rules")
    .select()
    .eq("user_id", userId)
    .order("start_date_iso");
  if (error) throw error;
  return ((data ?? []) as unknown as RecurringRuleRow[]).map(toRecurringRule);
}

export async function insertRecurringRule(input: NewRecurringRule): Promise<RecurringRule> {
  assertRuleInput(input);
  if (
    input.type === "transfer" &&
    input.accountId &&
    input.toAccountId &&
    input.accountId === input.toAccountId
  ) {
    throw new Error("Transfer rules need two different accounts.");
  }
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("recurring_rules")
    .insert({
      user_id: userId,
      type: input.type,
      amount_paise: input.amountPaise,
      category: input.category,
      note: input.note,
      pay_mode: input.payMode,
      ...(input.accountId ? { account_id: input.accountId } : {}),
      ...(input.toAccountId ? { to_account_id: input.toAccountId } : {}),
      tags: normalizeTags(input.tags),
      frequency: input.frequency,
      start_date_iso: input.startDateISO,
      ...(input.endDateISO ? { end_date_iso: input.endDateISO } : {}),
      last_posted_date_iso: null,
      is_paused: input.isPaused ?? false,
    })
    .select()
    .single();
  if (error) throw error;
  return toRecurringRule(data as unknown as RecurringRuleRow);
}

export async function updateRecurringRule(
  id: string,
  patch: RecurringRulePatch,
): Promise<RecurringRule | undefined> {
  const userId = await uid();
  const sb = getSupabase();
  const { data: current, error: fetchError } = await sb
    .from("recurring_rules")
    .select()
    .eq("id", id)
    .eq("user_id", userId)
    .single();
  if (isNoRows(fetchError)) return undefined;
  if (fetchError) throw fetchError;
  const merged = { ...toRecurringRule(current as unknown as RecurringRuleRow), ...patch };
  assertRuleInput(merged);
  const row: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (patch.type !== undefined) row["type"] = patch.type;
  if (patch.amountPaise !== undefined) row["amount_paise"] = patch.amountPaise;
  if (patch.category !== undefined) row["category"] = patch.category;
  if (patch.note !== undefined) row["note"] = patch.note;
  if (patch.payMode !== undefined) row["pay_mode"] = patch.payMode;
  if (patch.accountId !== undefined) row["account_id"] = patch.accountId;
  if (patch.toAccountId !== undefined) row["to_account_id"] = patch.toAccountId;
  if (patch.frequency !== undefined) row["frequency"] = patch.frequency;
  if (patch.startDateISO !== undefined) row["start_date_iso"] = patch.startDateISO;
  if (patch.endDateISO !== undefined) row["end_date_iso"] = patch.endDateISO;
  if (patch.isPaused !== undefined) row["is_paused"] = patch.isPaused;
  if (patch.tags !== undefined) row["tags"] = normalizeTags(patch.tags);
  const { data, error } = await sb
    .from("recurring_rules")
    .update(row)
    .eq("id", id)
    .eq("user_id", userId)
    .select()
    .single();
  if (isNoRows(error)) return undefined;
  if (error) throw error;
  return toRecurringRule(data as unknown as RecurringRuleRow);
}

export async function deleteRecurringRule(id: string): Promise<boolean> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("recurring_rules")
    .delete()
    .eq("id", id)
    .eq("user_id", userId)
    .select("id");
  if (error) throw error;
  return ((data ?? []) as unknown[]).length > 0;
}

export async function setRecurringRulePaused(
  id: string,
  isPaused: boolean,
): Promise<RecurringRule | undefined> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb
    .from("recurring_rules")
    .update({ is_paused: isPaused, updated_at: new Date().toISOString() })
    .eq("id", id)
    .eq("user_id", userId)
    .select()
    .single();
  if (isNoRows(error)) return undefined;
  if (error) throw error;
  return toRecurringRule(data as unknown as RecurringRuleRow);
}

/**
 * Idempotent auto-post of due recurring transactions: for each unpaused rule,
 * compute occurrence dates up to and including today, skip dates that already
 * have a transaction with the same (rule, date), insert the missing ones, and
 * advance last_posted_date_iso. Never double-posts.
 */
export async function ensureRecurringPosted(): Promise<void> {
  const userId = await uid();
  const sb = getSupabase();
  const today = todayISO();
  const now = new Date().toISOString();
  const rules = await fetchRecurringRules();
  for (const rule of rules) {
    if (rule.isPaused) continue;
    if (rule.startDateISO > today) continue;
    const lastPosted = rule.lastPostedDateISO ?? null;
    const due: string[] = [];
    for (let n = 0; n < 1000; n++) {
      const dateISO = recurringOccurrenceDate(rule.startDateISO, rule.frequency, n);
      if (dateISO > today) break;
      if (lastPosted !== null && dateISO <= lastPosted) continue;
      if (rule.endDateISO && dateISO > rule.endDateISO) break;
      due.push(dateISO);
    }
    if (due.length === 0) continue;
    const first = due[0] as string;
    const last = due[due.length - 1] as string;
    const { data: existing, error: fetchError } = await sb
      .from("transactions")
      .select("date_iso")
      .eq("user_id", userId)
      .eq("recurring_rule_id", rule.id)
      .gte("date_iso", first)
      .lte("date_iso", last);
    if (fetchError) throw fetchError;
    const posted = new Set(
      ((existing ?? []) as unknown as { date_iso: string }[]).map((r) => r.date_iso),
    );
    const missing = due.filter((d) => !posted.has(d));
    if (missing.length > 0) {
      const { error: insertError } = await sb.from("transactions").insert(
        missing.map((dateISO) => ({
          user_id: userId,
          type: rule.type,
          amount_paise: rule.amountPaise,
          category: rule.category,
          note: rule.note || "Recurring",
          date_iso: dateISO,
          pay_mode: rule.payMode,
          ...(rule.accountId ? { account_id: rule.accountId } : {}),
          ...(rule.toAccountId ? { to_account_id: rule.toAccountId } : {}),
          tags: [...rule.tags],
          recurring_rule_id: rule.id,
        })),
      );
      if (insertError) throw insertError;
    }
    const { error: updateError } = await sb
      .from("recurring_rules")
      .update({ last_posted_date_iso: last, updated_at: now })
      .eq("id", rule.id)
      .eq("user_id", userId);
    if (updateError) throw updateError;
  }
}

// ---- Tags ----

/** Every distinct tag used across transactions, sorted alphabetically. */
export async function fetchAllTags(): Promise<string[]> {
  const userId = await uid();
  const sb = getSupabase();
  const { data, error } = await sb.from("transactions").select("tags").eq("user_id", userId);
  if (error) throw error;
  const set = new Set<string>();
  for (const row of (data ?? []) as unknown as { tags: string[] | null }[]) {
    for (const tag of row.tags ?? []) set.add(tag);
  }
  return [...set].sort((a, b) => a.localeCompare(b));
}

// ---- Whole-DB load (AI engine / chat / notifications) ----

export async function loadFinanceDB(): Promise<FinanceDB> {
  const [
    transactions,
    budgets,
    bills,
    goals,
    holdings,
    accounts,
    customCategories,
    recurringRules,
  ] = await Promise.all([
    fetchTransactions(),
    fetchAllBudgets(),
    fetchBills(),
    fetchGoals(),
    fetchHoldings(),
    fetchAccounts(),
    fetchCustomCategories(),
    fetchRecurringRules(),
  ]);
  return {
    transactions,
    budgets,
    bills,
    goals,
    holdings,
    accounts,
    customCategories,
    recurringRules,
  };
}
