/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as MoreRouteImport } from './routes/more'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as StocksSymbolRouteImport } from './routes/stocks.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksSymbolRoute = StocksSymbolRouteImport.update({
  id: '/stocks/$symbol',
  path: '/stocks/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/budgets': typeof BudgetsRoute
  '/chat': typeof ChatRoute
  '/expenses': typeof ExpensesRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/readiness': typeof ReadinessRoute
  '/screener': typeof ScreenerRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/budgets': typeof BudgetsRoute
  '/chat': typeof ChatRoute
  '/expenses': typeof ExpensesRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/readiness': typeof ReadinessRoute
  '/screener': typeof ScreenerRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/budgets': typeof BudgetsRoute
  '/chat': typeof ChatRoute
  '/expenses': typeof ExpensesRoute
  '/goals': typeof GoalsRoute
  '/insights': typeof InsightsRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/readiness': typeof ReadinessRoute
  '/screener': typeof ScreenerRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bills'
    | '/budgets'
    | '/chat'
    | '/expenses'
    | '/goals'
    | '/insights'
    | '/more'
    | '/notifications'
    | '/portfolio'
    | '/readiness'
    | '/screener'
    | '/stocks/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bills'
    | '/budgets'
    | '/chat'
    | '/expenses'
    | '/goals'
    | '/insights'
    | '/more'
    | '/notifications'
    | '/portfolio'
    | '/readiness'
    | '/screener'
    | '/stocks/$symbol'
  id:
    | '__root__'
    | '/'
    | '/bills'
    | '/budgets'
    | '/chat'
    | '/expenses'
    | '/goals'
    | '/insights'
    | '/more'
    | '/notifications'
    | '/portfolio'
    | '/readiness'
    | '/screener'
    | '/stocks/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRoute
  BudgetsRoute: typeof BudgetsRoute
  ChatRoute: typeof ChatRoute
  ExpensesRoute: typeof ExpensesRoute
  GoalsRoute: typeof GoalsRoute
  InsightsRoute: typeof InsightsRoute
  MoreRoute: typeof MoreRoute
  NotificationsRoute: typeof NotificationsRoute
  PortfolioRoute: typeof PortfolioRoute
  ReadinessRoute: typeof ReadinessRoute
  ScreenerRoute: typeof ScreenerRoute
  StocksSymbolRoute: typeof StocksSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$symbol': {
      id: '/stocks/$symbol'
      path: '/stocks/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof StocksSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRoute,
  BudgetsRoute: BudgetsRoute,
  ChatRoute: ChatRoute,
  ExpensesRoute: ExpensesRoute,
  GoalsRoute: GoalsRoute,
  InsightsRoute: InsightsRoute,
  MoreRoute: MoreRoute,
  NotificationsRoute: NotificationsRoute,
  PortfolioRoute: PortfolioRoute,
  ReadinessRoute: ReadinessRoute,
  ScreenerRoute: ScreenerRoute,
  StocksSymbolRoute: StocksSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
